# Site settings
title: "Olaf.AI"
description: "Onward, Living A Future"
url: 'https://phanxuanphucnd.github.io/'
cover: images/cover.png
baseurl: ''
google_analytics: 'G-NA24071997'
disqus_shortname: 'OLAF.AI'

author:
  name: 'OLAF.AI'
  pronouns: "Onward, Living A Future"
  email: theolafwall@gmail.com
  github:  olaf-ai
  linkedin:  phanxuanphucnd
  google_scholar: ipcDPCQAAAAJ&hl=vi
  fb: theolafwall

collections_dir: my_collections
collections:
  about-us:
    output: true
    permalink: /:collection/:path
    title: "About Us"
    show: true

  stories:
    output: true
    permalink: /:collection/:path
    title: "Stories"
    show: true

defaults:
  -
    scope:
      path: "my_collections/*" # all files inside my_collections
    values:
      layout: "post" #post.html

# Build settings
destination: _site
# paginate: 10
# permalink: /:collection
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  mathjax: true  #use mathjax to process math equations
  input: GFM # use Github Flavored Markdown
  hard_wrap: false # do not replace newlines by <br>

# plugins:
#   - jekyll-paginate
#   - jekyll-spaceship

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']
